name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2  # v2
        with:
          flutter-version: "3.24"
          channel: stable

      - run: flutter pub get

      - run: flutter analyze

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2  # v2
        with:
          flutter-version: "3.24"
          channel: stable

      - run: flutter pub get

      - run: flutter test

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2  # v2
        with:
          flutter-version: "3.24"
          channel: stable

      - run: flutter pub get

      - run: flutter build apk --debug

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/*.apk
